[package]
name = "dogoap"
version = "0.3.0"
edition = "2021"
description = "dogoap"
license = "MIT"
homepage = "https://github.com/victorb/dogoap"

[dependencies]
bevy_reflect = "0.15.0-rc.2"
log = "0.4.22"
pathfinding = "4.10.0"
